### ISSUE TITLE
Disabling API access from notebook container.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/kubespawner#109]
Instead of:

```
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: no-api-access-please
          readOnly: true
```

to block access to service account token from within a container, why not use ``automountServiceAccountToken``?

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

From 1.6 you can define it on a ``Pod``.

Do you still need to support pre 1.6?
