### ISSUE TITLE
capabilities SYS_ADMIN ???

### ISSUE THREAD

**Issue by madsi1m** [jupyterhub/kubespawner#170]
Hi All, not sure if this is an issue or if i am simply doing it wrong.

I am trying to CapAdd SYS_ADMIN by adding the following to my `jupyterhub_config.py`:

```
c.KubeSpawner.singleuser_extra_container_config = [
    {
        'securityContext': {
            'capabilities': {
                'add' : 'SYS_ADMIN'
             }
         }
    }
]
```

When i do a docker inspect on a notebook container the CapAdd is null.

I can `c.KubeSpawner.singleuser_privileged = True` but i don't want to give everything to the notebook, just SYS_ADMIN

Ideas?

**Comment by yee379** [comment]
i'm trying to do the same thing: i noticed that `singleuser_extra_container_config` is deprecated, but there is a `extra_pod_config` but that doesn't work either.

    extra_pod_config = { 'securityContext': { 'capabilities': { 'add': [ 'SYS_ADMIN' ] }  } },

were you able to get this to work?

**Comment by madsi1m** [comment]
Nope but this does (yes i know it is bad)
`c.KubeSpawner.singleuser_privileged = True`

**Comment by stefanvangastel** [comment]
It would be nice to get this to work. I want users to be able to mount NFS shares in their containers (and not use 'public' volumes).

**Comment by stefanvangastel** [comment]
@yee379 @madsi1m fixed this using the following extra **annotation** on top of the `SYS_ADMIN` and `DAC_READ_SEARCH` capability added via the `extra_container_config`.

`container.apparmor.security.beta.kubernetes.io/notebook: unconfined`

**Comment by madsi1m** [comment]
How?

**Comment by stefanvangastel** [comment]
@madsi1m I'm using the [Zero to JupyterHub with Kubernetes](https://zero-to-jupyterhub.readthedocs.io/en/latest/ ) Helm chart so the config below is Helm / yaml specific. The keys match the regular config though.

```yml
singleuser:
  extraAnnotations:
    container.apparmor.security.beta.kubernetes.io/notebook: 'unconfined'
  profileList:
    - display_name: "Base env"
      kubespawner_override:
        extra_container_config:
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - SYS_ADMIN
              - DAC_READ_SEARCH
```
