### ISSUE TITLE
'singleuser_image_pull_policy' must be a unicode string

### ISSUE THREAD

**Issue by ManifoldFR** [jupyterhub/kubespawner#187]
Running the latest development image v0.7-d300249, with a config that specifies 
```yaml
singleuser:
  image:
    name: jupyter/scipy-notebook
    tag: 03b897d05f16
  defaultUrl: "/lab"
  storage:
    dynamic:
        storageClass: nfs
```
I do the usual helm upgrade, specifying the version and all.

However, the hub pod fails, and the `kubectl logs` gives me
```
traitlets.traitlets.TraitError: The 'singleuser_image_pull_policy' trait of a KubeSpawner instance must be a unicode string, but a value of None <class 'NoneType'> was specified.
```
which is quite odd.

To add, I had a similar issue with LDAPAuthenticator which also wanted a config, although I specified it in the YAML. I had to re-specify it in the `hub.extraConfig` to get it to stop failing the pod. Then I hit the above issue.
