### ISSUE TITLE
NFS volume mount not writeable

### ISSUE THREAD

**Issue by PaulMazzuca** [jupyterhub/kubespawner#249]
When mounting an NFS volume, the c.KubeSpawner.fs_gid config option does not seem to have any effect.  Is it possible to change the gid of the NFS volume so that it can be writeable?

As background, I more or less followed this tutorial https://danielfrg.com/blog/2016/09/10/jupyterhub-kubernetes-nfs/. I can see the volume in the spawned pod, but cannot change the gid so that it can be writeable.

**Comment by PaulMazzuca** [comment]
Update:  The initial permissions of the mounted NFS folder are
```
drwxr-xr-x 3 root   root  4096 Aug 21 15:24 shared
```

If I log in as root to the container, I can change the permissions
```
docker exec -u root -it 382fdc3aa0f3 bash
# now inside the container
chgrp 100 shared && chmod g+w shared
```

This then allows my users to write to the NFS mounted volume. So the question becomes how can I achieve the same through through the dockerspawner configuration, given that I already have  c.KubeSpawner.fs_gid = 100?

**Comment by cellador** [comment]
Have you found a workaround? I'm facing the exact same problem at the moment. Thanks!

**Comment by PaulMazzuca** [comment]
My last comment solves the problem, though it does require the manual step of logging directly into the container once to make the change.  I haven't been able to come up with a better solution.

**Comment by hans-permana** [comment]
I encountered the same issue and did the same thing as @PaulMazzuca . I hope someone comes up with a better solution, so that accessing NFS pod and changing the permission of each new user (can be in the scale of 00's) can be avoided.

**Comment by consideRatio** [comment]
The k8s option fsGroup as part of a pod's security context isn't respected by NFS in k8s currently. It may be in the future and so, but the typical solution is to add a initContainer that chowns the mounted volume to the user id.

**Comment by Falven** [comment]
@consideRatio 
> The k8s option fsGroup as part of a pod's security context isn't respected by NFS in k8s currently. It may be in the future and so, but the typical solution is to add a initContainer that chowns the mounted volume to the user id.

I've done this as such:
```yaml
# The use of an initContainer here is due to NFS's lack of automatic UID/GID handling.
  # NFS mounts in K8s don't automatically match the user and group IDs of the container,
  # often resulting in permission issues. An initContainer running as root can adjust permissions on the NFS mount
  # to match the expected user IDs, resolving these issues. This approach allows the main container to continue
  # running as a non-root user, maintaining security best practices by limiting root access to only the initContainer
  # which performs necessary setup tasks before the main application starts.
  initContainers:
    - name: init-nfs
      image: busybox
      command:
        - 'sh'
        - '-c'
        - |
          echo "Changing permissions for /mnt/data..."
          chown -R 1000:100 /mnt/data && echo "Permissions set successfully." || echo "Failed to set permissions."
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: azure-blob-volume
          mountPath: /mnt/data
```
And I can see success in the logs:
```shell
(base) falven@Franciscos-MBP jupyterhub % kubectl logs jupyter-brookie -c init-nfs                                                         
Changing permissions for /mnt/data...
Permissions set successfully.
```
However when I exec in...
```
jovyan@jupyter-brookie:~$ ls -al /mnt/data
total 4
drwxrwsrwx 2 root users    0 Dec 29 07:34 .
drwxr-xr-x 1 root root  4096 Dec 29 07:34 ..
```
It's still owned by root... any ideas?
