### ISSUE TITLE
We should set the PVC's volumeName, i think

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#274]
@hans-permana found the z2jh setting `singleuser.storage.dynamic.volumeNameTemplate`. We both thought that this could influence the naming of the dynamically created `PersistantVolume` objects. Our investigation led us to conclude that this is only the spawned pods volume reference under the pods `spec.volumes` that is named in this manner, while the actual `PersistantVolume` k8s object, which is to be provisioned by the cloud provider looking at the PVC object in turn created by KubeSpawner, is not getting a similar name. This is because the PVC kubespawner creates does not set the `spec.volumeName` field ([see reference documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#persistentvolumeclaimspec-v1-core)).

I think we should allow optionally setting the `volumeName` field of the PVC's spec through the `make_pvc` function in kubespawner. The Z2JH project can then later decide to utilize this option or not.

## Suggested action - Add config of `volumeName` here
https://github.com/jupyterhub/kubespawner/blob/481ec0926960927300c7355c48bd03230ee857f0/kubespawner/objects.py#L393-L433

#### Z2JH configuration ([inspect in the source code](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/4075094ba2dbffa031a111e308134e33f4956a7b/jupyterhub/values.yaml#L200-L204)):

```yaml
singleuser:
  storage:
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
```

#### Z2JH config of kubespawner based on Z2JH config:
```python
if storage_type == 'dynamic':
    pvc_name_template = get_config('singleuser.storage.dynamic.pvcNameTemplate')
    c.KubeSpawner.pvc_name_template = pvc_name_template
    volume_name_template = get_config('singleuser.storage.dynamic.volumeNameTemplate')
    c.KubeSpawner.storage_pvc_ensure = True
    set_config_if_not_none(c.KubeSpawner, 'storage_class', 'singleuser.storage.dynamic.storageClass')
    set_config_if_not_none(c.KubeSpawner, 'storage_access_modes', 'singleuser.storage.dynamic.storageAccessModes')
    set_config_if_not_none(c.KubeSpawner, 'storage_capacity', 'singleuser.storage.capacity')

    # Add volumes to singleuser pods
    c.KubeSpawner.volumes = [
        {
            'name': volume_name_template,
            'persistentVolumeClaim': {
                'claimName': pvc_name_template
            }
        }
    ]
    c.KubeSpawner.volume_mounts = [
        {
            'mountPath': get_config('singleuser.storage.homeMountPath'),
            'name': volume_name_template
        }
    ]
```

#### A spawned user pods specs
```yaml
spec:
  # ...
  volumes:
  - name: volume-erik-2esundell
    persistentVolumeClaim:
      claimName: claim-erik-2esundell
```

#### Docs about the `volumes` configurable on kubespawner

https://github.com/jupyterhub/kubespawner/blob/481ec0926960927300c7355c48bd03230ee857f0/kubespawner/spawner.py#L586-L611

#### Kubespawners actual usage of the volumes

https://github.com/jupyterhub/kubespawner/blob/481ec0926960927300c7355c48bd03230ee857f0/kubespawner/objects.py#L311-L312

**Comment by hans-permana** [comment]
This would also be useful to set the name of `hub-db-dir` pv. This is to prevent the creation of a new volume after each cluster creation.

**Comment by bitnik** [comment]
I just tried to create a PVC with `volumeName` set:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-test-volume-name
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: volume-test-name
```

But the creation of PVC not completed because I think it searches for a PV with this name and it doesn't exist. I commented the line with `volumeName` and this time PVC is created with PV with a random name. I am not completely sure but if `volumeName` config is set, in the code we first should create a PV with [`claimRef`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#persistentvolumespec-v1-core) to the PVC and when PVC is created, it will be bound it.
