### ISSUE TITLE
Regarding c.KubeSpawner.environment and the EnvVar structure's valueFrom field

### ISSUE THREAD

**Issue by qzchenwl** [jupyterhub/kubespawner#306]
I tried
```yaml
hub:
  extraConfig:
    jupyterlab: |
      c.KubeSpawner.extra_container_config = {
        "env": [{
          "name": "MY_POD_IP",
          "valueFrom": {
            "fieldRef": {
              "fieldPath": "status.podIP"
            }
          }
        }]
      }
```
But this will overwrite the default env, and cause error. Any way to append env instead of replace all env?

**Comment by zlanyi** [comment]
what you think about in deployment,yaml of  your helm chart?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
spec:
   ...
  template:
    ...
    spec:
      ...
      containers:
        ...
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
```

**Comment by qzchenwl** [comment]
@zlanyi This way would inject hub's POD_IP to hub container. What I need is for singleuser container.

**Comment by zlanyi** [comment]
@qzchenwl no, it's only declaration. What do you want to do?
Do you want to have the IP of Hub on the Notebook server?

**Comment by qzchenwl** [comment]
@zlanyi I want the notebook server to know which IP can be used for communicate with outside world. e.g. which IP should others use to connect to notebook server/kernel.

**Comment by abinet** [comment]
I have same problem.
Trying to setup jupyter notebook with spark connecting to yarn cluster.
For this i need SPARK_LOCAL_IP to be set in the notebook pod. Currently it seems there is no way to add environment variable with "valueFrom" instead of "value".

**Comment by consideRatio** [comment]
Hmmm kubernetes question, can uoyou specify/hardcode a ClusterIP on creation?

**Comment by consideRatio** [comment]
I think the key issue is that you want to write env in a more complicated form than just key:value where these are strings, we should perhaps try to support something like this though.

Hmmm oh wait okay now i was thinking of the helm chart config values under singleuser.env, but hmmm perhaps you can do this from the config anyhow?

Hmmmms eh it would be a technical ugly workaround... hmmmm... mindwrangling... kubespawner has a env field, right?

can you do something like you do above, but use the extend function instead on c.KubeSpawner.environment ?

**Comment by consideRatio** [comment]
```python
c.KubeSpawner.environment.extend({
          "name": "MY_POD_IP",
          "valueFrom": {
            "fieldRef": {
              "fieldPath": "status.podIP"
            }
          }
        })
```

**Comment by abinet** [comment]
Thanks @consideRatio  but this not works for me.
I'm getting the error message that Dict does not have "extend" method

**Comment by consideRatio** [comment]
@abinet ah, so c.KubeSpawner.environment it is a dictionary rather than an array... and that is a limitation because kubespawner have assumed all environment varibles will be hardcoded strings...

Okay, I think this will require kubespawner to adjust.

Then, until kubespawner is remade, the ugly option I then think may be required is something like this:

```yaml
hub:
  extraConfig:
    jupyterlab: |
      env = [{
          "name": "MY_POD_IP",
          "valueFrom": {
            "fieldRef": {
              "fieldPath": "status.podIP"
            }
          }
        }]
      env.extend({'name': key, 'value': value} for key, value in c.KubeSpawner.environment.items())
      c.KubeSpawner.extra_container_config = {
        "env": env
      }
```

**Comment by abinet** [comment]
@consideRatio  we are almost there. But c.KubeSpawner.environment does not deliver the env variables from created by Spawner and they will be overridden later.
I'm not very familiar with python. How I can get run KubeSpawner.get_env() properly?

**Comment by consideRatio** [comment]
@abinet oh, hmmm, oh? If that is the case, perhaps you can run this logic in a pre_spawn_hook then?

```
def my_hook(spawner):
    # spawner is refers to the specific users KubeSpawner instance (one is created per user)
    # run the logic here...

c.KubeSpawner.pre_spawn_hook = my_hook
```

**Comment by abinet** [comment]
Thank you @consideRatio! Last point was really the hit.

Here is my solution for now:

```
hub:
  extraConfig:
    ipaddress: |
      from kubernetes import client

      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].env.append(client.V1EnvVar("MY_POD_IP", None, client.V1EnvVarSource(None, client.V1ObjectFieldSelector(None, "status.podIP"))))
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook

```

**Comment by consideRatio** [comment]
Wieee thanks for sharing this solution!!

**Comment by TomAugspurger** [comment]
FWIW, I think that something like https://github.com/jupyterhub/kubespawner/pull/461 adding `extra_env` would be pretty useful.  In my case, I have my jupyterhub helm config settings some environment variables:

```yaml
jupyterhub:
  singleuser:
    extraEnv:
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
...
```

that I want to apply to all profiles. Then I have some profiles (e.g. with GPUs) that should have some extra environment variables. It'd be nice to have

```
...
    profileList:
      - gpu
        extra_env: {'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility'}
```

to append (or update / overwrite) those extra environment variables, while keeping the common ones. Would something like a `KubeSpawner.extra_env` be in scope?
