### ISSUE TITLE
Improve test coverage of kubespawner

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/kubespawner#313]
Given that Kubespawner is a core component of many Jupyter Infra tools (mybinder.org, jupyterhub, binderhub), it'd be great if we could improve the test coverage a bit. 

As of creating this issue, we're at **69%**, which is a good start! Here's a badge that'll get updated as more tests improve coverage.

[![codecov](https://codecov.io/gh/jupyterhub/kubespawner/branch/master/graph/badge.svg)](https://codecov.io/gh/jupyterhub/kubespawner)

If any folks would like to make improvements to tests, it would be greatly appreciated!

**Comment by betatim** [comment]
One thing that worked well (even if it required a lot of hard work!) for repo2docker was to use the following codecov check settings:
```
comment: off
coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
         target: 20% 
```
It prevents the bot from polluting PR discussions with comments and it nudges you to not merge PRs that decrease coverage. It also asks for at least 20% of the lines you changed to be covered.

I think the nudge of "at least don't reduce coverage" has the net result that coverage increases over time. Without being too much of a "you have to eat your vegetables" kind of annoyance.
