### ISSUE TITLE
Unable to claim existing PVC in Kubespawner

### ISSUE THREAD

**Issue by srams2018** [jupyterhub/kubespawner#320]
iam trying to use the same volumemount created by Jupyterhub in every pod through kubespawner class, but getting below error.
```yaml
      # Jupyterhub yaml
      volumes:
       - name: data-home
         persistentVolumeClaim:
          claimName: rdb-demo
         volumeMounts:
           - name: data-home
             mountPath: /apps1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rdb-demo
spec:
  storageClassName: rbd-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi 
```

```python
# jupyter_config.py
c.KubeSpawner.volume_mounts = [
    {
        'mountPath': '/apps1',
        'name': 'anaconda'
    }
]
```

```
Error:-
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-rams\" is invalid: spec.containers[0].volumeMounts[0].name: Not found: \"anaconda\"","reason":"Invalid","details":{"name":"jupyter-rams","kind":"Pod","causes":[{"reason":"FieldValueNotFound","message":"Not found: \"anaconda\"","field":"spec.containers[0].volumeMounts[0].name"}]},"code":422}
```

Is there any issue with the jupyter_config.py configuration here?
