### ISSUE TITLE
Spawn Failed Message: Harmless Error but Could Turn Off Novice Users

### ISSUE THREAD

**Issue by julienchastang** [jupyterhub/kubespawner#328]
[Upon recommendation](https://gitter.im/jupyterhub/jupyterhub) from @yuvipanda , I am submitting an issue here.

I administer a few JupyterHub servers. I have noticed on many occasions that when I access the JupyterHub I will get a 

`Spawn failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

as can be seen here: https://photos.app.goo.gl/egp1XmwUCiNo3TdGA

Accompanying this error is [this stack trace](https://gist.github.com/julienchastang/98608b32453410301b2461e571c6bfb3).

The workaround is easy. Simply go the the Home menu and click 'Start My Server'. The problem, however, could be disconcerting for new users. Is there anyway to avoid this spawn error?

I am running:

- jupyterhub version 0.9.4
- jupyterhub-singleuser version 1.0.0.

with Zero to JupyterHub. The docker container that gets spawned inherits from `jupyter/minimal-notebook` and it is rather large (~2GB).

Running on NSF Jetstream (OpenStack) Cloud at TACC

Edit: [Here is the Zero to JupyterHub config (roughly)](https://github.com/Unidata/xsede-jetstream/blob/master/vms/jupyter/example_secrets.yaml).

**Comment by julienchastang** [comment]
Possibly related https://github.com/jupyterhub/jupyterhub/issues/2083

Also 

```
hub:
  extraConfig: |-
    c.Spawner.http_timeout = 30
    c.Spawner.start_timeout = 30
```

has no effect. 

What is weird, is it hits that spawn error (both visible on the web page and URL) *the instant* you navigate to the hub. All timeouts seem to be ignored.

**Comment by consideRatio** [comment]
I'm not 100% about these aspects, but try for example:

```
c.KubeSpawner.start_timeout = 900
```

Is this traitlet a generic Spawner thing? Overridden? Would it work to use either? Must you use one but not the other?

Many questions... answers I have not.

![image](https://user-images.githubusercontent.com/3837114/59724622-cdc48180-922a-11e9-9cfa-a5e251db4df1.png)

**Comment by julienchastang** [comment]
I tried

```yaml
hub:
  extraConfig: |-
    c.KubeSpawner.start_timeout = 180
    c.KubeSpawner.http_timeout = 120
```

and I already had

```yaml
singleuser:
  startTimeout: 600
```

but sadly, the result is still the same.

**Comment by julienchastang** [comment]
Interestingly, I can replicate this problem with a minimal (https via letencrypt and github oauth) configuration:

```yaml
hub:
  cookieSecret: "xxx"
proxy:
  secretToken: "xxx"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - jupyter.org
  tls:
      - hosts:
         - jupyter.org
        secretName: certmanager-tls-jupyterhub

auth:
  type: github
  github:
    clientId: "xxx"
    clientSecret: "xxx"
    callbackUrl: "https://jupyter.org:443/oauth_callback"
  admin:
    users:
      - adminuser
```

Since that rules out a bunch of my stuff, I wonder if it has anything to do with the openstack platform I run on.
