### ISSUE TITLE
 KubeSpawner override for profile overrides existing spawner.environment

### ISSUE THREAD

**Issue by scivm** [jupyterhub/kubespawner#390]
I have a pre_spawn_start where I get the AD_TOKEN and put it to the spawner.environment dictionary.   My single user profile sets environment variables also.  kubespawner is using these variables to override the spawner environment which causes my single user notebook to fail because it requires a AD_TOKEN (own requirement).  I think the profile environment dictionary should append to the existing spawner environment variables if they are not the same?  

Also, if you try a second spawn just after the first failed one then both the AD_TOKEN and the override variables are set in spawner.environment and spawn works fine.

Single user override in z2h config.yaml:
   ```
- display_name: "Datascience environment"
      description: "Python, R, and Julia."
      default: true
      kubespawner_override:
        image: scivm/jupyter-datascience:latest
        cpu_guarantee: 1
        cpu_limit: 2
        mem_guarantee: "2096M"
        mem_limit: "8192M"
        environment:
             datasource_driverClassName: org.postgresql.Driver
```

It can be seen that in pre_spawn_start the AD_TOKEN is set, but then in modify_pod_hook, only the postgres environment variable is still set.
```
printing spawner.environment from pre_spawn_start
{'AD_TOKEN': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsI...'

[D 2020-01-26 18:01:03.351 JupyterHub user:556] Calling Spawner.start for shamberger michael (ext)
[D 2020-01-26 18:01:03.351 JupyterHub spawner:1988] Applying KubeSpawner override for profile 'Datascience environment'
[D 2020-01-26 18:01:03.351 JupyterHub spawner:1995] .. overriding KubeSpawner value cpu_guarantee=1
[D 2020-01-26 18:01:03.351 JupyterHub spawner:1995] .. overriding KubeSpawner value cpu_limit=2
[D 2020-01-26 18:01:03.351 JupyterHub spawner:1995] .. overriding KubeSpawner value environment={'datasource_driverClassName': 'org.postgresql.Driver'}
[D 2020-01-26 18:01:03.352 JupyterHub spawner:1995] .. overriding KubeSpawner value image=scivm/jupyter-datascience:latest
[D 2020-01-26 18:01:03.352 JupyterHub spawner:1995] .. overriding KubeSpawner value mem_guarantee=2096M
[D 2020-01-26 18:01:03.352 JupyterHub spawner:1995] .. overriding KubeSpawner value mem_limit=8192M
[I 2020-01-26 18:01:03.409 JupyterHub pages:347] shamberger michael (ext) is pending spawn
[I 2020-01-26 18:01:03.413 JupyterHub log:174] 200 GET /hub/spawn-pending/shamberger%20michael%20%28ext%29 (shamberger michael (ext)@172.19.0.1) 8.20ms
[I 2020-01-26 18:01:03.418 JupyterHub spawner:1769] PVC claim-shamberger-20michael-20-28ext-29 already exists, so did not create new pvc.
print spawner.environment in modify_pod_hook
{'datasource_driverClassName': 'org.postgresql.Driver'}
```
