### ISSUE TITLE
Environment variable "NB_USER":"{username}" doesn't expand

### ISSUE THREAD

**Issue by atanasov-ka** [jupyterhub/kubespawner#395]
I put the following environment variable to KubeSpawner but it seems that expansion is not supported over env variables.

dict(singleuser_image_spec="....",
environment={
                  'CHOWN_HOME': 'yes'
                  **'NB_USER': '{username}'**
},
....
)

If that isn't possible to fix maybe to add another property called for example "environment_expandable" which will allow to receive such variables?

**Comment by manics** [comment]
If you need to dynamically set environment variables you can use a `pre_spawn_start` hook:
https://jupyterhub.readthedocs.io/en/latest/reference/authenticators.html#using-auth-state

**Comment by consideRatio** [comment]
I know you can use `"NB_USER": "$(JUPYTERHUB_USER)"` to rely on k8s environment expansion instead of Kubespawners expansion, where the JUPYTERHUB_USER environment variable is [set here](https://github.com/jupyterhub/jupyterhub/blob/0317fd63fa1dac4d709b4f95738e74c5c408da6c/jupyterhub/spawner.py#L764) by the Spawner base class that KubeSpawner inherits from.

**Comment by cointreauu** [comment]
@consideRatio  Hello, I was searching how to set environment variable in user's pod which is launched by kubespawner, and found your comments...
```yaml

singleuser:
  profileList:
    - display_name: "Test"
      kubespawner_override:
        environment:
          MY_TEST: "$(JUPYTERHUB_USER)"
          DBUS_SESSION_BUS_ADDRESS: "$(dbus-launch --sh-syntax | awk -F\' 'NR==1{print $2}')"

```

I want to execute `dbus-launch --sh-syntax | awk -F\' 'NR==1{print $2}'` and then, assign its output to DBUS_SESSION_BUS_ADDRESS.
However, DBUS_SESSION_BUS_ADDRESS was literally assigned with `dbus-launch --sh-syntax | awk -F\' 'NR==1{print $2}'` .


As an another option, I tried to add hub.extraConfig as well.
(referenced [here](https://github.com/jupyterhub/kubespawner/issues/306#issuecomment-789718547)) 
It just failed to launch pod....

```yaml
hub:
  extraConfig:
    dbus_set_config: |
        async def pre_spawn_hook(spawner):
            output = os.popen("dbus-launch --sh-syntax").read().split('\n')
            spawner.environment.update({
                "DBUS_SESSION_BUS_ADDRESS": output[0].split("'")[1]
                })

        c.KubeSpawner.pre_spawn_hook = pre_spawn_hook
```


How can I add dynamically generated variable into user's notebook pod as environment variable?
