### ISSUE TITLE
[Help] Is there some way by which we can inject notebook configuration via kubespawner

### ISSUE THREAD

**Issue by akhilputhiry** [jupyterhub/kubespawner#396]
I need to inject or modify some default notebook configuration while launching the notebooks via kube spawner.  I could think of mounting the config file as volume, is there anyother way by which we can pass the configuration on to notebook.

**Comment by ABVitali** [comment]
If I understood well your question I think that what you need is a configmap object that you can mount in your jupyterhub pod.

Just to give you an example:

```
kind: ConfigMap
apiVersion: v1
metadata:
   name: 'jupyterhub-cfg'
   labels:
      app: 'jupyterhub'
data:
   jupyterhub_config.py: |-
        c.KubeSpawner.default_url = '/lab'

        c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'

        c.KubeSpawner.start_timeout = 15 * 60

        c.JupyterHub.services = [
            {
                'name': 'cull-idle',
                'admin': True,
                'command': ['cull-idle-servers', '--timeout=600'],
            }
        ]

        c.KubeSpawner.service_account = 'jupyterhub-sa'
        c.KubeSpawner.namespace = 'jupyterhub-namespace'

        c.KubeSpawner.user_storage_pvc_ensure = True

        c.KubeSpawner.pvc_name_template = '{username}-jupyterhub-nb-pvc'
        c.KubeSpawner.user_storage_capacity = '5g'
        c.KubeSpawner.storage_access_modes = ['ReadWriteOnce']
        c.KubeSpawner.storage_class = 'standard'
        c.KubeSpawner.volumes = [
            {
                'name': 'data',
                'persistentVolumeClaim': {
                    'claimName': c.KubeSpawner.pvc_name_template
                }
            }
        ]

       ... 
       and so on with all the configuration you want to add.
```
After this, assuming that you deploy a Deployment kubernetes object, you should insert in it something like this:

```
apiVersion: apps/v1
kind: Deployment
...
    containers:
    - name: jupyterhub
      ...
      volumeMounts:
                - name: config
                  mountPath: /opt/app-root/configs (I'm pretty sure that you could choose a different path)

    volumes:
       - name: config
         configMap:
            name: jupyterhub-cfg
            defaultMode: 420
```

I know that the example is partial and it is more a hint.
I hope this can help you to solve your problem!
