### ISSUE TITLE
Ability to restrict the options provided in profile_list per user

### ISSUE THREAD

**Issue by pknutti** [jupyterhub/kubespawner#439]
### Proposed change
It would be nice to have a feature to hide or show configured profiles per user.

### Who would use this feature?
Anyone who doesn't want to see all configured profiles 

### (Optional): Suggest a solution
It would be nice if there is a possiblility to add a whitelist to singleusers profilelist as shown below:

```
singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: '2343e33dec46'
    pullPolicy: Always
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      users:
        - user1
        - user2
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
```
