### ISSUE TITLE
Allow setting extraContainers, extraVolumes, etc as dicts

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#468]
### Proposed change

Right now, extraContainers, extraVolumes, extraVolumeMounts, etc are lists. This matches what the k8s API needs. However, this makes overriding them in helm config *very* difficult, as there's no way to spend to a list or modify individual elements.

For example, if you have this config in your generic-to-all-hubs helm config:

```
hub:
  initContainers:
      - name: templates-clone
        image: alpine/git
```

You can't actually add another container to this in an override without copying the original. You'll have to do something like:

```
hub:
  initContainers:
      - name: templates-clone
        image: alpine/git
      - name: something-else
        image: alpine
```

This can get out of sync quite quickly.

In addition to treating extraContainers, etc as lists, we can *also* treat them as dicts, with `name` being the key. This lets helm overrides work as they should. We have done this in the past to `extraConfig` and friends in zero to jupyterhub, so doing this here would be valuble.

### Alternative options

Do this in zero to jupyterhub, but that's probably the wrong place for this.

### Who would use this feature?

Anyone doing a deployment of many hubs that are similar to each other.
