### ISSUE TITLE
Setting Spawner.environment does not seem to affect KubeSpawner.get_env()

### ISSUE THREAD

**Issue by danielballan** [jupyterhub/kubespawner#485]
Running Helm Chart version 0.11.1, I find that setting:

```yaml
hub:
  extraConfig:
    00-spawner-env-config: |
      c.KubeSpawner.environment = {"TEST_ENV": "HELLO"}
```

works as expected, setting `TEST_ENV` in the user environment, but

```yaml
hub:
  extraConfig:
    00-spawner-env-config: |
      c.KubeSpawner.environment = {"TEST_ENV": "HELLO"}
```

has no effect on the user environment.

I'm sure this kind of configuration merging has worked for me in other contexts, and [the traitlets Configurable docs are really clear on this exact point](https://traitlets.readthedocs.io/en/stable/config.html#class-based-configuration-inheritance).

I have checked this a couple times to check that I'm not getting confused about what I'm seeing. It is definitely the case that setting the config `Spawner` instead of `KubeSpawner` does not set the environment variable. For my immediate purposes, this is a sufficient workaround, but it would be good to understand what is happening.

Originally reported in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2062 as Point (3). Sent here by @consideRatio.
