### ISSUE TITLE
Jupyterhub cannot change Pod Name Template

### ISSUE THREAD

**Issue by v1r7u** [jupyterhub/kubespawner#528]
### Bug description
It looks like it is not possible to change the default pod-naming strategy `jupyter-{username}--{servername}`.

#### Expected behaviour
KubeSpawner should allow changing pod naming approach

#### Actual behaviour
I used three different variants and none of them works:
1. 
```
singleuser:
    podNameTemplate: podname-{userid}
```
2. 
```
singleuser:
    profileList:
        - display_name: test
            kubespawner_override:
                pod_name_template: override-{userid}
```
3. 
```
hub:
    extraConfig:
        kubeSpawnerCfg: |
            c.KubeSpawner.pod_name_template = "config-{userid}"
```

I even tried all three at once, but I'm getting default `jupyter-{username}--{servername}` 😄 

I also tried to dive into sources and I cannot find an issue on `zero-to-jupyterhub-k8s` side. I suspect changing this value could be not supported by kubespawner itself:
1. `pod_name_template` is used **only at Spawner initialization** time: https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L214
2. the rest of the code seems to use already generated `pod_name`, for example this one looks like pod creation request: https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L1817-L1818
3. so far I cannot find how exactly z2jh applies the configuration, but I think it tries to change the naming template **after KubeSpawner is initialized**

If you could help to confirm or deny my findings, I think I can help to solve the issue

### How to reproduce
Use snippets from `Behavior` section

### Your personal set up
```
Kubernetes: v1.19.7
Helm: v3.6.0
Jupyterhub charts: 0.11.1-1.0.0
```
