### ISSUE TITLE
Merge volumes from both Kubespawner override and the default configuration?

### ISSUE THREAD

**Issue by cyrilcros** [jupyterhub/kubespawner#550]
I am not sure if this goes into KubeSpawner or Zero to Jupyterhub, or if this is bug. 

### Proposed change

On the Helm chart v1.2.0, when you use the `kubespawner_override` `volumes` and `volume_mounts` option, you lose the default mounts common to every profile, from `singleuser.storage.extraVolumes`. More annoyingly, you lose the default mount of the dynamic `pvcNameTemplate` PVC. That also means your work in your `/home/jovyan` doesn't get saved....

Could we always merge the extra volume overrides with the default ones, rather than squashing them? Maybe a `add_default_volumes` boolean option, in case people use the same mount path with different volumes?

### Alternative options

- I am guessing I could also just ditch the single user customizations, start with a default profile that has a YAML anchor like `kubespawner_override:  &common-bits` and just reuse it across profiles
- add a generic `merge_z2h_strategy` flag that would allow you to either `squash` your Z2H singleuser defaults, or try to `merge` them together with your overrides. No granular choices...
-  add a flag with a list of pod specs to merge rather than squash `merge_with_defaults: [volumeMounts, volumes, labels, nodeSelector]`

```
singleuser:
  storage:
    extraVolumes: [AA]
    extraVolumeMounts: [BB]
  profileList:
  - display_name: My merged profile
    description: Merge defaults with overrides
    merge_with_defaults: 
    - volumeMounts
    - volumes
    kubespawner_override:
      volumes: [XX]
      volumeMounts: [YY]
```
Yielding a pod with volumes AA+XX + `pvcNameTemplate` and volumeMounts BB+YY + `volumeNameTemplate`. The solution depends on when you do the merging of options, before sending them to KubeSpawner I guess? Or we could generate manifests from the default and the overriden profile, merge them, and then send a final product back to KubeSpawner? That would have to be done in Python.

### Who would use this feature?

Zero to Jupyterhub users who use the profile features / alter the `singleuser` config and want to merge them....

FYI I wanted to use a GPU in Jupyterhub, usually you would use `extra_resource_limits:  nvidia.com/gpu: "1" ` but I couldn't directly use the `k8s-device-plugin` in Kubernetes 1.22 due to a cgroup issue. I needed to add a lot of `/dev/nvidia-XXX` `hostPath` volumes. I noticed that removed my default extra volumes and the dynamic one when I restarted my server and couldn't see the files I was working with...

**Comment by cyrilcros** [comment]
I think as another possibility, the kubespawner docs should show how to get the "default behavior" of the Helm chart. I think for the storage it would be something like...
```
storage_pvc_ensure: true
volume_mounts: 
- name: volume-{username}{servername} 
   mountPath: /home/jovyan 
volumes:
- name: volume-{username}{servername}
  persistentVolumeClaim: 
    claimName: claim-{username}{servername}
```
