### ISSUE TITLE
Kubernetes Operator For Jupyter

### ISSUE THREAD

**Issue by akhilputhiry** [jupyterhub/kubespawner#715]
This might not be the right place to ask this question.
Apologies for spamming 

### Proposed change
Can we have a Kubernetes Operator for Jupyter
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/

May be we could have a CRD like this and we could create an operator using [kopf](https://kopf.readthedocs.io/en/stable/) or something similar

```yaml
apiVersion: jupyter.com/v1
kind: Notebook
metadata:
  name: my-notebook
spec:
  machine:
    cpu: 1
    memory: 1
  git:
    repo: https://github.com/jupyterhub/kubespawner.git
```
