### ISSUE TITLE
subpath of {username} is escaped when it should not be

### ISSUE THREAD

**Issue by jabbera** [jupyterhub/kubespawner#754]
### Bug description

When using extraVolumeMounts and subPath: {username} is escaped when it should not be. This causes a user with name: svc-blah who has a home folder: nfsroot/svc-blah to be not found because kubespawner is looking for nfsroot/svc-2dblah incorrectly. File systems don't have the same limitations as k8s and should use the unescaped name IMO:

```
    extraVolumeMounts:
    - name: claim-nfs-user-root
      mountPath: /mnt/z
      subPath: '{username}'
```

#### Expected behaviour

username should not be escaped

#### Actual behaviour

username is escaped
