### ISSUE TITLE
Some _template options don't work when defined in profile_list profiles

### ISSUE THREAD

**Issue by AlexHill** [jupyterhub/kubespawner#761]
https://github.com/jupyterhub/kubespawner/issues/528 touches on this but the issue is more general than described there.

### Bug description

Some of the `*_template` options are expanded in `KubeSpawner.__init__()` and never again. Overriding them in profile_list profiles therefore doesn't work - you can override the template, but since the template has already been expanded, overriding doesn't produce the desired effect.

See e.g. [pvc_name](https://github.com/jupyterhub/kubespawner/blob/cd17869ed4fe0eb9e65dd3bc7b994687a2a72b8e/kubespawner/spawner.py#L194), which is set in __init__ and then used in [get_pod_manifest()](https://github.com/jupyterhub/kubespawner/blob/cd17869ed4fe0eb9e65dd3bc7b994687a2a72b8e/kubespawner/spawner.py#L2091) as-is. Instead, I think pvc_name_template should be expanded in get_pod_manifest().

#### Expected behaviour

Expansion of templates should be deferred wherever possible so that their overridden values can be respected.

#### Actual behaviour

Some templates are expanded during __init__ and never again, so overriding them has no effect.

### How to reproduce

Deploy z2jh with 
```
  singleuser:
    profileList:
      - display_name: Override test
        default: true
        kubespawner_override:
          service_account: default
          volumes:
            - name: user-home
              persistentVolumeClaim:
                claimName: override-claim-{userid}--{servername}
          volume_mounts:
            - name: user-home
              mountPath: /home/jovyan
          pvc_name_template: override-claim-{userid}--{servername}
```

And try to launch your server. It will fail, because the volume definitions are expanded after overrides are applied, but the PVC name is not.
