### ISSUE TITLE
pvc_name is expanded before user options/profiles are loaded

### ISSUE THREAD

**Issue by manics** [jupyterhub/kubespawner#877]
### Bug description
Reported in

`pvc_name` is expanded in `__init__`, which means `pvc_name_template` can't be overridden in `kubespawner_overrides`:
https://github.com/jupyterhub/kubespawner/blob/5ac45e946ae39a2949c50a0b1a2bee79077b1351/kubespawner/spawner.py#L208

### How to reproduce
Reported in https://discourse.jupyter.org/t/creating-1-pvc-per-profile-and-per-user/31755

With Z2JH 4.1.0:
```yaml
hub:
  db:
    type: sqlite-pvc

proxy:
  service:
    type: NodePort
    nodePorts:
      http: 31080

singleuser:
  profileList:
    - display_name: "profile1"
      description: "desc1"
      kubespawner_override:
        pvc_name_template: claim-{username}-profile1
    - display_name: "profile2"
      description: "desc2"
      kubespawner_override:
        pvc_name_template: claim-{username}-profile2

debug:
  enabled: true
```

#### Expected behaviour

`pvc_name` follows the template `pvc_name_template` if it is overriden in `kubespawner_overrides`.

#### Actual behaviour

The overridden template is ignored, `claim-{username}` is used for all profiles.

### Your personal set up
https://killercoda.com/manics/scenario/jupyterhub-kubernetes
