### ISSUE TITLE
Ephemeral and emptyDir volume mounts in profile

### ISSUE THREAD

**Issue by PyroGun** [jupyterhub/kubespawner#886]
### Bug description

Adding volume and volume mount for storage type ephemeral or emptyDir does nothing

### How to reproduce

1. Create a jupyter profile in kubespawner config.yaml
2. Add 
```
volumes:
  - name: example
    emptyDir:
        sizeLimit: 5Gi
volume_mounts:
  - name: example
    mountPath: /dev/shm
```
to created profile
3. Deploy new configuration to Z2JH Kubernetes cluster
4. Check that on pod spawn with selected profile has no extra volume mounts in yaml spec

#### Expected behaviour

volume mount is appended in volume mounts section of pod yaml spec

#### Actual behaviour

`volumes` and `volume_mounts` options seem to be ignored

### Your personal set up

using Z2JH Kuberenetes deployment

 - OS:
Kubernetes v1.29
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
