### ISSUE TITLE
Request GPU

### ISSUE THREAD

**Issue by zonca** [jupyterhub/kubespawner#93]
I cannot find a way to request a GPU via `kubespawner`, the equivalend `kubectl` specification is:

```
spec:                                                                                                                               
  containers:                                                                                                                       
    - image: XXXX                                                                             
      resources:                                                                                                                    
        limits:                                                                                                                     
          alpha.kubernetes.io/nvidia-gpu: 1 # requesting 1 GPU 
```

**Comment by yuvipanda** [comment]
Thanks to @foxish there's now a 'extra_resource_limits' and 'extra_resource_guarantees' you can use for this!

**Comment by naeemkhan12** [comment]
how can i specify 'extra_resource_limits' and 'extra_resource_guarantees'  in values.yaml file. for nvidia gpu
```
cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  extraResource:
```

**Comment by twbrandon7** [comment]
@naeemkhan12 Just add these parameters in extraConfig.
For example:
```
hub:
  cookieSecret: "<COOKIE>"
  db:
    type: sqlite-pvc
  extraConfig: |-
    c.KubeSpawner.extra_resource_limits = {"nvidia.com/gpu": "1"}
    c.KubeSpawner.extra_resource_guarantees = {"nvidia.com/gpu": "1"}
```
